# Generated by Django 4.2.9 on 2026-06-07 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genealogy', '0001_initial'),
        ('clans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('husband_name', models.CharField(blank=True, help_text='If husband not in archive', max_length=200)),
                ('husband_community', models.CharField(blank=True, help_text='If from outside the Pojulu community', max_length=200)),
                ('wife_name', models.CharField(blank=True, help_text='If wife not in archive', max_length=200)),
                ('wife_community', models.CharField(blank=True, help_text='If from outside the Pojulu community', max_length=200)),
                ('year', models.CharField(blank=True, max_length=10)),
                ('place', models.CharField(blank=True, max_length=300)),
                ('payam', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('children_names', models.TextField(blank=True, help_text='Names of children from this union')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('husband', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marriages_as_husband', to='genealogy.person')),
                ('husband_clan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marriages_husband_clan', to='clans.clan')),
                ('wife', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marriages_as_wife', to='genealogy.person')),
                ('wife_clan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marriages_wife_clan', to='clans.clan')),
            ],
            options={
                'verbose_name': 'Marriage Record',
                'ordering': ['-year'],
            },
        ),
    ]
