# Generated by Django 4.2.9 on 2026-06-08 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('clan_admin', 'Clan Administrator'), ('genealogy_admin', 'Genealogy & Families Administrator'), ('memorial_admin', 'Memorial Records Administrator'), ('cultural_admin', 'Cultural Archive & Media Administrator'), ('elder_admin', 'Elder Interviews Administrator'), ('achievement_admin', 'Achievements Administrator'), ('content_admin', 'Full Content Administrator')], max_length=30)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_admins', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Profile',
                'ordering': ['-created_at'],
            },
        ),
    ]
