# Generated by Django 4.2.9 on 2026-06-07 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genealogy', '0001_initial'),
        ('clans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElderInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elder_name', models.CharField(max_length=200)),
                ('payam', models.CharField(blank=True, max_length=100)),
                ('approximate_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('interview_location', models.CharField(blank=True, max_length=200)),
                ('interviewer', models.CharField(max_length=200)),
                ('language', models.CharField(default='Pojulu / English', max_length=100)),
                ('summary', models.TextField(help_text='Summary of topics covered and key information shared')),
                ('transcript', models.TextField(blank=True, help_text='Full transcript of the interview')),
                ('topics_covered', models.CharField(blank=True, help_text='Comma-separated list of topics covered', max_length=600)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='interviews/audio/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='interviews/video/')),
                ('video_url', models.URLField(blank=True, help_text='External video link')),
                ('photo_of_elder', models.ImageField(blank=True, null=True, upload_to='interviews/photos/')),
                ('is_published', models.BooleanField(default=False, help_text='Only published interviews appear on the site')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clans.clan')),
                ('clans_mentioned', models.ManyToManyField(blank=True, related_name='mentioned_in_interviews', to='clans.clan')),
                ('elder_person', models.ForeignKey(blank=True, help_text='Link to person record if they exist in archive', null=True, on_delete=django.db.models.deletion.SET_NULL, to='genealogy.person')),
            ],
            options={
                'verbose_name': 'Elder Interview',
                'ordering': ['-interview_date', 'elder_name'],
            },
        ),
    ]
