# Generated by Django 4.2.9 on 2026-06-07 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=320, unique=True)),
                ('record_type', models.CharField(choices=[('song', 'Traditional Song'), ('proverb', 'Proverb & Wisdom'), ('ceremony', 'Cultural Ceremony'), ('story', 'Story & Oral Narrative'), ('folklore', 'Folklore & Myth'), ('dance', 'Traditional Dance'), ('language', 'Language & Linguistics'), ('other', 'Other')], max_length=20)),
                ('content', models.TextField(help_text='The main content — lyrics, text, description')),
                ('translation', models.TextField(blank=True, help_text='English translation if in Pojulu language')),
                ('context', models.TextField(blank=True, help_text='When, how, and why this is used / performed')),
                ('performers', models.CharField(blank=True, help_text='Who traditionally performs or recites this', max_length=300)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='cultural/audio/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube/Vimeo link to a recording')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cultural/images/')),
                ('language', models.CharField(default='Pojulu', max_length=100)),
                ('source', models.CharField(blank=True, help_text='Source: elder name, interview date, document ref', max_length=300)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clan', models.ForeignKey(blank=True, help_text='Clan this record is associated with', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clans.clan')),
            ],
            options={
                'verbose_name': 'Cultural Record',
                'ordering': ['record_type', 'title'],
            },
        ),
    ]
