# Generated by Django 4.2.9 on 2026-06-07 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genealogy', '0001_initial'),
        ('clans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(help_text='Full name of the person being honoured', max_length=200)),
                ('category', models.CharField(choices=[('leadership', 'Leadership & Governance'), ('education', 'Education & Academia'), ('culture', 'Culture & Arts'), ('service', 'Community Service'), ('sport', 'Sport & Athletics'), ('business', 'Business & Enterprise'), ('religion', 'Faith & Religion'), ('military', 'Military & Security'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(help_text='One-line achievement title', max_length=500)),
                ('description', models.TextField()),
                ('year', models.CharField(blank=True, max_length=10)),
                ('source', models.CharField(blank=True, help_text='Source / reference for this achievement', max_length=300)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='clans.clan')),
                ('person', models.ForeignKey(blank=True, help_text='Link to person record if they exist in the archive', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='genealogy.person')),
            ],
            options={
                'verbose_name': 'Achievement',
                'ordering': ['-year', 'person_name'],
            },
        ),
    ]
