# Generated by Django 4.2.9 on 2026-06-07 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Ladu Family'", max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('payam', models.CharField(blank=True, choices=[('lainya_centre', 'Lainya Centre (Headquarters)'), ('kupera', 'Kupera'), ('kenyi', 'Kenyi'), ('wuji', 'Wuji'), ('mukaya', 'Mukaya'), ('wonduruba', 'Wonduruba (Juba County)'), ('yei_county', 'Yei County'), ('diaspora', 'Diaspora'), ('other', 'Other')], max_length=20)),
                ('origin_village', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, help_text="Brief description of this family's history")),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_set', to='clans.clan')),
            ],
            options={
                'verbose_name': 'Family',
                'verbose_name_plural': 'Families',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=200)),
                ('other_names', models.CharField(blank=True, help_text='Traditional names, nicknames, or other known names', max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=1)),
                ('payam', models.CharField(blank=True, choices=[('lainya_centre', 'Lainya Centre (Headquarters)'), ('kupera', 'Kupera'), ('kenyi', 'Kenyi'), ('wuji', 'Wuji'), ('mukaya', 'Mukaya'), ('wonduruba', 'Wonduruba (Juba County)'), ('yei_county', 'Yei County'), ('diaspora', 'Diaspora'), ('other', 'Other')], max_length=20)),
                ('birth_year', models.CharField(blank=True, max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=300)),
                ('is_deceased', models.BooleanField(default=False)),
                ('death_year', models.CharField(blank=True, max_length=20)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('death_place', models.CharField(blank=True, max_length=300)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='persons/photos/')),
                ('biography', models.TextField(blank=True)),
                ('occupation', models.CharField(blank=True, max_length=300)),
                ('education', models.TextField(blank=True)),
                ('current_residence', models.CharField(blank=True, max_length=300)),
                ('contributions', models.TextField(blank=True, help_text='Notable contributions to the Pojulu community')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_elder', models.BooleanField(default=False, help_text='Mark if this person is/was a community elder')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.CharField(blank=True, max_length=200)),
                ('clan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_set', to='clans.clan')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_set', to='genealogy.family')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_father', to='genealogy.person', verbose_name='Father')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_mother', to='genealogy.person', verbose_name='Mother')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
