# Generated by Django 4.2.9 on 2026-06-11 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.RemoveField(
            model_name='person',
            name='education',
        ),
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.TextField(blank=True, help_text='Current physical address'),
        ),
        migrations.AddField(
            model_name='person',
            name='email_contact',
            field=models.EmailField(blank=True, help_text='Contact email (optional)', max_length=254),
        ),
        migrations.AddField(
            model_name='person',
            name='hobbies',
            field=models.TextField(blank=True, help_text='Hobbies and personal interests'),
        ),
        migrations.AddField(
            model_name='person',
            name='languages_spoken',
            field=models.CharField(blank=True, help_text='e.g. Pojulu, Arabic, English', max_length=300),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number (optional)', max_length=80),
        ),
        migrations.AddField(
            model_name='person',
            name='profile_pdf',
            field=models.FileField(blank=True, help_text='Upload full profile PDF document', null=True, upload_to='persons/pdfs/'),
        ),
        migrations.AddField(
            model_name='person',
            name='religion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='skills_talents',
            field=models.TextField(blank=True, help_text='Skills, talents, and gifts'),
        ),
        migrations.AlterField(
            model_name='family',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='family',
            name='payam',
            field=models.CharField(blank=True, choices=[('lainya_centre', 'Lainya Centre (Headquarters)'), ('kupera', 'Kupera'), ('kenyi', 'Kenyi'), ('wuji', 'Wuji'), ('mukaya', 'Mukaya'), ('wonduruba', 'Wonduruba (Juba County)'), ('yei_county', 'Yei County'), ('diaspora', 'Diaspora'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='contributions',
            field=models.TextField(blank=True, help_text='Community contributions and service'),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_elder',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='other_names',
            field=models.CharField(blank=True, help_text='Traditional or other known names', max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='payam',
            field=models.CharField(blank=True, choices=[('lainya_centre', 'Lainya Centre (Headquarters)'), ('kupera', 'Kupera'), ('kenyi', 'Kenyi'), ('wuji', 'Wuji'), ('mukaya', 'Mukaya'), ('wonduruba', 'Wonduruba (Juba County)'), ('yei_county', 'Yei County'), ('diaspora', 'Diaspora'), ('other', 'Other')], max_length=50),
        ),
        migrations.CreateModel(
            name='PersonMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('document', 'Document / PDF'), ('video', 'Video'), ('audio', 'Audio Recording')], default='photo', max_length=20)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('file', models.FileField(help_text='Photo, PDF, audio, or video file', upload_to='persons/media/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube/Vimeo link (alternative to file upload)')),
                ('caption', models.TextField(blank=True)),
                ('date_taken', models.CharField(blank=True, help_text='Date or approximate year', max_length=100)),
                ('is_profile_photo', models.BooleanField(default=False, help_text='Use as main profile photo')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='genealogy.person')),
            ],
            options={
                'verbose_name': 'Person Media',
                'ordering': ['order', 'media_type'],
            },
        ),
        migrations.CreateModel(
            name='PersonEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(help_text='School, college, or university name', max_length=300)),
                ('qualification', models.CharField(help_text='e.g. Bachelor of Arts, KCSE Certificate', max_length=300)),
                ('field_of_study', models.CharField(blank=True, help_text='Subject or discipline', max_length=300)),
                ('start_year', models.CharField(blank=True, max_length=10)),
                ('end_year', models.CharField(blank=True, max_length=10)),
                ('is_current', models.BooleanField(default=False, help_text='Currently studying here')),
                ('honors', models.CharField(blank=True, help_text='e.g. First Class, Distinction', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('certificate', models.FileField(blank=True, help_text='Upload certificate or transcript (PDF/JPG)', null=True, upload_to='persons/education/')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order (0 = most recent)')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_history', to='genealogy.person')),
            ],
            options={
                'verbose_name': 'Education Record',
                'ordering': ['order', '-start_year'],
            },
        ),
        migrations.CreateModel(
            name='PersonCareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(help_text='Organisation or employer name', max_length=300)),
                ('position', models.CharField(help_text='Job title or role', max_length=300)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('start_year', models.CharField(blank=True, max_length=10)),
                ('end_year', models.CharField(blank=True, max_length=10)),
                ('is_current', models.BooleanField(default=False, help_text='Currently working here')),
                ('description', models.TextField(blank=True, help_text='Responsibilities, achievements, and contributions in this role')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_history', to='genealogy.person')),
            ],
            options={
                'verbose_name': 'Career Record',
                'ordering': ['order', '-start_year'],
            },
        ),
    ]
