# Generated by Django 4.2.9 on 2026-06-07 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_type', models.CharField(choices=[('person', 'Person / Family Member'), ('clan', 'Clan History'), ('memorial', 'Memorial Record'), ('marriage', 'Marriage Record'), ('achievement', 'Achievement'), ('cultural', 'Cultural Record'), ('elder', 'Elder Interview Request'), ('correction', 'Correction / Update to Existing Record')], max_length=30)),
                ('submitter_name', models.CharField(max_length=200)),
                ('submitter_email', models.EmailField(max_length=254)),
                ('submitter_phone', models.CharField(blank=True, max_length=50)),
                ('submitter_location', models.CharField(blank=True, max_length=200)),
                ('submitter_relationship', models.CharField(help_text='Your relationship to this record (e.g. grandson, clan coordinator)', max_length=300)),
                ('subject_name', models.CharField(blank=True, help_text='Name of the person/clan/record being submitted', max_length=300)),
                ('clan_name', models.CharField(blank=True, max_length=200)),
                ('payam', models.CharField(blank=True, max_length=100)),
                ('year', models.CharField(blank=True, max_length=20)),
                ('content', models.TextField(help_text='Main information / narrative for this submission')),
                ('additional_notes', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, help_text='Document, photo, or audio file', null=True, upload_to='submissions/attachments/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('in_review', 'Under Review'), ('approved', 'Approved & Published'), ('rejected', 'Rejected'), ('needs_info', 'More Information Needed')], default='pending', max_length=20)),
                ('reviewer_notes', models.TextField(blank=True, help_text='Internal notes from the reviewer')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Community Submission',
                'verbose_name_plural': 'Community Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
