# Generated by Django 4.2.9 on 2026-06-11 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('slug', models.SlugField(blank=True, max_length=440, unique=True)),
                ('post_type', models.CharField(choices=[('news', 'News'), ('event', 'Event'), ('announcement', 'Announcement'), ('story', 'Community Story'), ('update', 'Archive Update')], default='news', max_length=20)),
                ('excerpt', models.TextField(help_text='Brief summary shown on news cards (2–3 sentences)', max_length=600)),
                ('content', models.TextField(help_text='Full article or event description')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='news/covers/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo URL — shown as video card')),
                ('event_date', models.DateTimeField(blank=True, help_text='For events: start date and time', null=True)),
                ('event_end_date', models.DateTimeField(blank=True, help_text='For events: end date', null=True)),
                ('event_location', models.CharField(blank=True, max_length=400)),
                ('is_upcoming', models.BooleanField(default=False, help_text='Mark as upcoming event')),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False, help_text='Pin as featured story on homepage')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'News Post',
                'verbose_name_plural': 'News & Events',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('document', 'Document'), ('video', 'Video')], default='photo', max_length=20)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('file', models.FileField(upload_to='news/media/')),
                ('caption', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='news.newspost')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
