# Generated by Django 4.2.9 on 2026-06-07 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('payam', models.CharField(choices=[('lainya_centre', 'Lainya Centre (Headquarters)'), ('kupera', 'Kupera'), ('kenyi', 'Kenyi'), ('wuji', 'Wuji'), ('mukaya', 'Mukaya'), ('wonduruba', 'Wonduruba (Juba County)'), ('yei_county', 'Yei County'), ('diaspora', 'Diaspora'), ('other', 'Other')], max_length=20)),
                ('tagline', models.CharField(blank=True, help_text='One-sentence description shown on cards', max_length=300)),
                ('description', models.TextField(help_text='General overview of the clan')),
                ('origin_story', models.TextField(blank=True, verbose_name='Origin & Founding Story')),
                ('migration_history', models.TextField(blank=True, verbose_name='Migration & Settlement History')),
                ('territorial_notes', models.TextField(blank=True, verbose_name='Territorial & Land History')),
                ('cultural_practices', models.TextField(blank=True, verbose_name='Cultural Practices & Customs')),
                ('traditional_beliefs', models.TextField(blank=True, verbose_name='Traditional Beliefs & Spirituality')),
                ('historical_events', models.TextField(blank=True, verbose_name='Important Historical Events')),
                ('sub_clans', models.TextField(blank=True, help_text='Known sub-clans or branches (comma-separated)')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified by Editorial Board')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allied_clans', models.ManyToManyField(blank=True, to='clans.clan', verbose_name='Allied / Connected Clans')),
            ],
            options={
                'verbose_name': 'Clan',
                'verbose_name_plural': 'Clans',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('year', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField()),
                ('significance', models.CharField(blank=True, max_length=200)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='clans.clan')),
            ],
            options={
                'verbose_name': 'Historical Event',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='ClanChief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(default='Chief', help_text='e.g. Chief, Paramount Chief, Elder', max_length=100)),
                ('start_year', models.CharField(blank=True, max_length=10)),
                ('end_year', models.CharField(blank=True, max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order (lower = earlier)')),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chiefs', to='clans.clan')),
            ],
            options={
                'verbose_name': 'Chief / Elder',
                'verbose_name_plural': 'Chiefs / Elders',
                'ordering': ['order', 'start_year'],
            },
        ),
    ]
