# Generated by Django 4.2.9 on 2026-06-11 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClanBoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the boma', max_length=200)),
                ('history', models.TextField(help_text='History and background of this boma')),
                ('current_leader', models.CharField(blank=True, help_text='Current payam/boma administrator or chief', max_length=200)),
                ('past_leaders', models.TextField(blank=True, help_text='Names of past leaders with their approximate years')),
                ('population', models.CharField(blank=True, help_text='Estimated population of this boma', max_length=100)),
                ('main_activities', models.TextField(blank=True, help_text='Main economic activities of people in this boma')),
                ('location_description', models.TextField(blank=True, help_text='Location, borders, and landmarks')),
                ('year_established', models.CharField(blank=True, max_length=20)),
                ('infrastructure', models.TextField(blank=True, help_text='Schools, health facilities, churches, markets in this boma')),
                ('notable_persons', models.TextField(blank=True, help_text='Notable people from this boma')),
                ('notes', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Boma',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='clan',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='clanchief',
            options={'ordering': ['order', 'start_year'], 'verbose_name': 'Chief / Elder'},
        ),
        migrations.AddField(
            model_name='clan',
            name='border_east',
            field=models.CharField(blank=True, help_text='Eastern border', max_length=400),
        ),
        migrations.AddField(
            model_name='clan',
            name='border_north',
            field=models.CharField(blank=True, help_text='Northern border: neighbouring community or landmark', max_length=400),
        ),
        migrations.AddField(
            model_name='clan',
            name='border_south',
            field=models.CharField(blank=True, help_text='Southern border', max_length=400),
        ),
        migrations.AddField(
            model_name='clan',
            name='border_west',
            field=models.CharField(blank=True, help_text='Western border', max_length=400),
        ),
        migrations.AddField(
            model_name='clan',
            name='infrastructure',
            field=models.TextField(blank=True, help_text='Schools, health facilities, roads, churches, markets'),
        ),
        migrations.AddField(
            model_name='clan',
            name='landscape',
            field=models.TextField(blank=True, help_text='Description of the landscape, terrain, and natural features'),
        ),
        migrations.AddField(
            model_name='clan',
            name='main_activities',
            field=models.TextField(blank=True, help_text='Main economic activities: farming, fishing, cattle-keeping, trade, etc.'),
        ),
        migrations.AddField(
            model_name='clan',
            name='population_estimate',
            field=models.CharField(blank=True, help_text='Estimated current population', max_length=100),
        ),
        migrations.AddField(
            model_name='clan',
            name='rivers',
            field=models.TextField(blank=True, help_text='Rivers, streams, and water bodies in clan territory'),
        ),
        migrations.AddField(
            model_name='clanchief',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='clans/chiefs/'),
        ),
        migrations.AlterField(
            model_name='clan',
            name='allied_clans',
            field=models.ManyToManyField(blank=True, to='clans.clan'),
        ),
        migrations.AlterField(
            model_name='clan',
            name='cultural_practices',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='clan',
            name='description',
            field=models.TextField(help_text='General overview'),
        ),
        migrations.AlterField(
            model_name='clan',
            name='historical_events',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='clan',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clan',
            name='migration_history',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='clan',
            name='origin_story',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='clan',
            name='payam',
            field=models.CharField(choices=[('lainya_centre', 'Lainya Centre (Headquarters)'), ('kupera', 'Kupera'), ('kenyi', 'Kenyi'), ('wuji', 'Wuji'), ('mukaya', 'Mukaya'), ('wonduruba', 'Wonduruba (Juba County)'), ('yei_county', 'Yei County'), ('diaspora', 'Diaspora'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='clan',
            name='sub_clans',
            field=models.TextField(blank=True, help_text='Known sub-clans (comma-separated)'),
        ),
        migrations.AlterField(
            model_name='clan',
            name='tagline',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='clan',
            name='territorial_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='clan',
            name='traditional_beliefs',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='clanchief',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clanchief',
            name='title',
            field=models.CharField(default='Chief', max_length=100),
        ),
        migrations.AlterField(
            model_name='clanevent',
            name='significance',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.CreateModel(
            name='ClanMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('document', 'Document / PDF'), ('video', 'Video'), ('audio', 'Audio Recording')], default='photo', max_length=20)),
                ('section', models.CharField(choices=[('general', 'General'), ('history', 'Historical'), ('geography', 'Geography & Landscape'), ('rivers', 'Rivers & Water'), ('boma', 'Boma'), ('leaders', 'Leadership'), ('culture', 'Cultural'), ('community', 'Community Life'), ('infrastructure', 'Infrastructure'), ('events', 'Events & Celebrations'), ('achievements', 'Achievements')], default='general', help_text='Which section of the clan page this media belongs to', max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('file', models.FileField(blank=True, null=True, upload_to='clans/media/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube/Vimeo link')),
                ('caption', models.TextField(blank=True)),
                ('date_taken', models.CharField(blank=True, help_text='Date or approximate year', max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('boma', models.ForeignKey(blank=True, help_text='Link to a specific boma if this media is boma-specific', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='clans.clanboma')),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='clans.clan')),
            ],
            options={
                'verbose_name': 'Clan Media',
                'ordering': ['section', 'order'],
            },
        ),
        migrations.AddField(
            model_name='clanboma',
            name='clan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bomas', to='clans.clan'),
        ),
    ]
