# Generated by Django 4.2.9 on 2026-06-07 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genealogy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemorialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tribute', models.TextField(help_text='Extended tribute / remembrance text')),
                ('survived_by', models.TextField(blank=True, help_text='List of surviving family members')),
                ('burial_place', models.CharField(blank=True, max_length=300)),
                ('epitaph', models.CharField(blank=True, help_text='Short memorable quote or epitaph', max_length=300)),
                ('submitted_by', models.CharField(blank=True, max_length=200)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memorial', to='genealogy.person')),
            ],
            options={
                'verbose_name': 'Memorial Record',
                'ordering': ['-created_at'],
            },
        ),
    ]
